language: python
python:
  - "3.6"
install:
  - make install
# Run the style and unit tests
jobs:
  include:
    - stage: testing
      script: make coverage
    - stage: style
      script: make style
after_success:
  - coveralls
